/**
 * data.js — Pre-parsed profile data for the Romeo matchmaking engine.
 *
 * All 20 profiles are embedded directly as JavaScript objects to avoid
 * CSV parsing complexity. Every field value is the exact text from the
 * hackathon_matchmaking_dataset.csv file.
 *
 * Exports:
 *   - rawProfiles: Array of 20 profile objects
 *   - getRawProfile(id): Lookup a single profile by participant_id
 */

export const rawProfiles = [
  {
    participant_id: 'P01',
    name: 'Aarav Malhotra',
    age: '30',
    gender: 'M',
    city: 'Kolkata',
    occupation: 'Data Scientist',
    education: 'M.Sc Statistics, ISI Kolkata',
    annual_income: 'INR 22 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Physical Touch',
    perfect_sunday: 'Honestly, hopping on a flight somewhere I haven\'t been, maybe followed by any excuse to dance, honestly if I have the energy.',
    core_value: 'Probably being family-oriented -- family comes first for me, always -- I try to make time for them no matter how busy things get.',
    shows_care_via: 'Small physical gestures, a hand on the shoulder, sitting close -- that\'s my language.',
    quality_time_means: 'small physical gestures, a hand on the shoulder, sitting close -- that\'s my language, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly smoking is a hard no for me too.',
    friends_describe_you: 'Pretty expressive -- what I feel usually shows on my face -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Hopping on a flight somewhere I haven\'t been -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more ambitious instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do any excuse to dance, honestly, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m pretty expressive -- what i feel usually shows on my face.'
  },
  {
    participant_id: 'P02',
    name: 'Aditya Nair',
    age: '31',
    gender: 'M',
    city: 'Kolkata',
    occupation: 'Musician',
    education: 'B.Mus, Rabindra Bharati University',
    annual_income: 'INR 8 LPA (gig-based, variable)',
    relationship_history: 'Never married',
    children_preference: 'Open either way',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, a few hours lost in a good game, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being loyal -- once someone\'s in my corner, I\'m all in -- loyalty means a lot to me.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I\'m keeping it open for now and letting things develop naturally.',
    favorite_hobby: 'A few hours lost in a good game -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more family-oriented instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P03',
    name: 'Anaya Verma',
    age: '28',
    gender: 'F',
    city: 'Chandigarh',
    occupation: 'Musician',
    education: 'B.Mus, Delhi School of Music',
    annual_income: 'INR 7 LPA (gig-based, variable)',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Vegetarian',
    love_language: 'Physical Touch',
    perfect_sunday: 'Honestly, any excuse to dance, honestly, maybe followed by hopping on a flight somewhere I haven\'t been if I have the energy.',
    core_value: 'Probably being ambitious -- I\'m pretty driven -- I always want to be building toward something bigger.',
    shows_care_via: 'Small physical gestures, a hand on the shoulder, sitting close -- that\'s my language.',
    quality_time_means: 'small physical gestures, a hand on the shoulder, sitting close -- that\'s my language, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Smoking is a hard no for me, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Any excuse to dance, honestly -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more creative instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do hopping on a flight somewhere I haven\'t been, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P04',
    name: 'Arjun Varma',
    age: '28',
    gender: 'M',
    city: 'Ahmedabad',
    occupation: 'Marketing Lead',
    education: 'MBA Marketing, MICA',
    annual_income: 'INR 18 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, getting lost in a good book for a few hours, maybe followed by trying out a new recipe in the kitchen if I have the energy.',
    core_value: 'Probably being independent -- I like having my own space and being able to stand on my own two feet.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'Pretty expressive -- what I feel usually shows on my face -- that\'s usually what people say about me.',
    relationship_goal: 'I\'m keeping it open for now and letting things develop naturally.',
    favorite_hobby: 'Getting lost in a good book for a few hours -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more loyal instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do trying out a new recipe in the kitchen, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m pretty expressive -- what i feel usually shows on my face.'
  },
  {
    participant_id: 'P05',
    name: 'Dev Chauhan',
    age: '29',
    gender: 'M',
    city: 'Ahmedabad',
    occupation: 'Consultant',
    education: 'B.Tech + MBA, NMIMS',
    annual_income: 'INR 20 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Quality Time',
    perfect_sunday: 'Honestly, wandering through a gallery or just sketching something, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being ambitious -- I\'m pretty driven -- I always want to be building toward something bigger.',
    shows_care_via: 'I make sure we get real, undistracted time together, phones away.',
    quality_time_means: 'I make sure we get real, undistracted time together, phones away, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'Direct, no games -- I\'d rather say the honest thing early than let it sit -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Wandering through a gallery or just sketching something -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more compassionate instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m direct, no games -- i\'d rather say the honest thing early than let it sit.'
  },
  {
    participant_id: 'P06',
    name: 'Diya Iyer',
    age: '26',
    gender: 'F',
    city: 'Mumbai',
    occupation: 'Doctor',
    education: 'MBBS, Grant Medical College',
    annual_income: 'INR 16 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, a few hours lost in a good game, maybe followed by any excuse to dance, honestly if I have the energy.',
    core_value: 'Probably being creative -- I need some kind of creative outlet or I feel a bit stuck.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly smoking is a hard no for me too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'A few hours lost in a good game -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more adventurous instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do any excuse to dance, honestly, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P07',
    name: 'Ishaan Bose',
    age: '33',
    gender: 'M',
    city: 'Chennai',
    occupation: 'Consultant',
    education: 'MBA, Great Lakes Chennai',
    annual_income: 'INR 28 LPA',
    relationship_history: 'Divorced, no children',
    children_preference: 'Open either way',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Physical Touch',
    perfect_sunday: 'Honestly, trying out a new recipe in the kitchen, maybe followed by walking around with my camera looking for something worth shooting if I have the energy.',
    core_value: 'Probably being family-oriented -- family comes first for me, always -- I try to make time for them no matter how busy things get.',
    shows_care_via: 'Small physical gestures, a hand on the shoulder, sitting close -- that\'s my language.',
    quality_time_means: 'small physical gestures, a hand on the shoulder, sitting close -- that\'s my language, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'I struggle with someone who has no drive or direction, and honestly someone who shuts down instead of talking things through too.',
    friends_describe_you: 'Direct, no games -- I\'d rather say the honest thing early than let it sit -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Trying out a new recipe in the kitchen -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more ambitious instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do walking around with my camera looking for something worth shooting, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m direct, no games -- i\'d rather say the honest thing early than let it sit.'
  },
  {
    participant_id: 'P08',
    name: 'Ishita Singh',
    age: '28',
    gender: 'F',
    city: 'Hyderabad',
    occupation: 'Entrepreneur',
    education: 'MBA, ISB Hyderabad',
    annual_income: 'INR 30 LPA equivalent (business income, variable)',
    relationship_history: 'Never married',
    children_preference: 'Does not want children',
    smoking_habit: 'Non-smoker (strong dealbreaker on this)',
    drinking_habit: 'Social drinker',
    diet: 'Vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, catching a live gig, even a small one, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being independent -- I like having my own space and being able to stand on my own two feet.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Smoking is a hard no for me, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'Catching a live gig, even a small one -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more ambitious instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P09',
    name: 'Kabir Sharma',
    age: '31',
    gender: 'M',
    city: 'Pune',
    occupation: 'Product Manager',
    education: 'MBA, IIM Ahmedabad',
    annual_income: 'INR 35 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, any excuse to dance, honestly, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being intellectual -- I love a good debate or a book that makes me think differently.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Wanting completely different things out of life is the big one, and honestly someone who shuts down instead of talking things through too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'Any excuse to dance, honestly -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more adventurous instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P10',
    name: 'Karan Chopra',
    age: '34',
    gender: 'M',
    city: 'Bengaluru',
    occupation: 'Entrepreneur',
    education: 'B.E. Computer Science, RVCE Bengaluru',
    annual_income: 'INR 40 LPA equivalent (business income, variable)',
    relationship_history: 'Divorced, one child (daughter, 6, lives with him on weekends)',
    children_preference: 'Open either way, already co-parenting',
    smoking_habit: 'Occasional smoker (socially, at work events)',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, any excuse to dance, honestly, maybe followed by hopping on a flight somewhere I haven\'t been if I have the energy.',
    core_value: 'Probably being family-oriented -- family comes first for me, always -- I try to make time for them no matter how busy things get.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'A bit quiet at first, but very steady once you get to know me -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Any excuse to dance, honestly -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more spiritual instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do hopping on a flight somewhere I haven\'t been, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m a bit quiet at first, but very steady once you get to know me.'
  },
  {
    participant_id: 'P11',
    name: 'Kavya Menon',
    age: '26',
    gender: 'F',
    city: 'Jaipur',
    occupation: 'Consultant',
    education: 'B.Tech + MBA, IIM Kozhikode',
    annual_income: 'INR 19 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, spending a few hours volunteering somewhere local, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being loyal -- once someone\'s in my corner, I\'m all in -- loyalty means a lot to me.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Smoking is a hard no for me, and honestly wanting completely different things out of life is the big one too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'Spending a few hours volunteering somewhere local -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more compassionate instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P12',
    name: 'Meera Joshi',
    age: '31',
    gender: 'F',
    city: 'Ahmedabad',
    occupation: 'Consultant',
    education: 'MBA, XLRI Jamshedpur',
    annual_income: 'INR 26 LPA',
    relationship_history: 'Divorced, no children',
    children_preference: 'Open either way',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, catching a live gig, even a small one, maybe followed by a trail I haven\'t done before if I have the energy.',
    core_value: 'Probably being adventurous -- I get restless if I\'m not trying something new every few months.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly wanting completely different things out of life is the big one too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'I\'m keeping it open for now and letting things develop naturally.',
    favorite_hobby: 'Catching a live gig, even a small one -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more loyal instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do a trail I haven\'t done before, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P13',
    name: 'Nikhil Rao',
    age: '29',
    gender: 'M',
    city: 'Pune',
    occupation: 'Software Engineer',
    education: 'B.Tech CSE, COEP Pune',
    annual_income: 'INR 24 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Gifts',
    perfect_sunday: 'Honestly, hopping on a flight somewhere I haven\'t been, maybe followed by a solid gym session or a long run if I have the energy.',
    core_value: 'Probably being ambitious -- I\'m pretty driven -- I always want to be building toward something bigger.',
    shows_care_via: 'I like to surprise them with something small and thoughtful, just because.',
    quality_time_means: 'I like to surprise them with something small and thoughtful, just because, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'A bit quiet at first, but very steady once you get to know me -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'Hopping on a flight somewhere I haven\'t been -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more compassionate instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do a solid gym session or a long run, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m a bit quiet at first, but very steady once you get to know me.'
  },
  {
    participant_id: 'P14',
    name: 'Nisha Gupta',
    age: '25',
    gender: 'F',
    city: 'Hyderabad',
    occupation: 'Journalist',
    education: 'B.A. Mass Communication, Osmania University',
    annual_income: 'INR 9 LPA',
    relationship_history: 'Never married',
    children_preference: 'Open either way',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, walking around with my camera looking for something worth shooting, maybe followed by any excuse to dance, honestly if I have the energy.',
    core_value: 'Probably being loyal -- once someone\'s in my corner, I\'m all in -- loyalty means a lot to me.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'Pretty expressive -- what I feel usually shows on my face -- that\'s usually what people say about me.',
    relationship_goal: 'I\'m keeping it open for now and letting things develop naturally.',
    favorite_hobby: 'Walking around with my camera looking for something worth shooting -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more ambitious instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do any excuse to dance, honestly, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m pretty expressive -- what i feel usually shows on my face.'
  },
  {
    participant_id: 'P15',
    name: 'Priya Desai',
    age: '29',
    gender: 'F',
    city: 'Chennai',
    occupation: 'Product Manager',
    education: 'MBA, IIM Bangalore',
    annual_income: 'INR 32 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Vegetarian',
    love_language: 'Quality Time',
    perfect_sunday: 'Honestly, spending a few hours volunteering somewhere local, maybe followed by wandering through a gallery or just sketching something if I have the energy.',
    core_value: 'Probably being independent -- I like having my own space and being able to stand on my own two feet.',
    shows_care_via: 'I make sure we get real, undistracted time together, phones away.',
    quality_time_means: 'I make sure we get real, undistracted time together, phones away, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'I struggle with someone who has no drive or direction, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'Spending a few hours volunteering somewhere local -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more spiritual instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do wandering through a gallery or just sketching something, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P16',
    name: 'Riya Kulkarni',
    age: '32',
    gender: 'F',
    city: 'Hyderabad',
    occupation: 'UX Designer',
    education: 'B.Des, NID Ahmedabad',
    annual_income: 'INR 21 LPA',
    relationship_history: 'Never married',
    children_preference: 'Open either way',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Physical Touch',
    perfect_sunday: 'Honestly, a solid gym session or a long run, maybe followed by trying out a new recipe in the kitchen if I have the energy.',
    core_value: 'Probably being ambitious -- I\'m pretty driven -- I always want to be building toward something bigger.',
    shows_care_via: 'Small physical gestures, a hand on the shoulder, sitting close -- that\'s my language.',
    quality_time_means: 'small physical gestures, a hand on the shoulder, sitting close -- that\'s my language, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Smoking is a hard no for me, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'A solid gym session or a long run -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Definitely someone who lights up a room.',
    self_improvement_area: 'Probably patience -- and being a bit more creative instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do trying out a new recipe in the kitchen, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P17',
    name: 'Rohan Mehta',
    age: '31',
    gender: 'M',
    city: 'Chandigarh',
    occupation: 'Musician',
    education: 'Diploma, Trinity College of Music (distance)',
    annual_income: 'INR 9 LPA (gig-based, variable)',
    relationship_history: 'Never married',
    children_preference: 'Does not want children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, spending a few hours volunteering somewhere local, maybe followed by catching a live gig, even a small one if I have the energy.',
    core_value: 'Probably being compassionate -- I can\'t walk past someone who needs help -- it\'s just how I\'m wired.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Heavy drinking is something I really can\'t be around long-term, and honestly wanting completely different things out of life is the big one too.',
    friends_describe_you: 'Pretty expressive -- what I feel usually shows on my face -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'Spending a few hours volunteering somewhere local -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more loyal instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do catching a live gig, even a small one, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m pretty expressive -- what i feel usually shows on my face.'
  },
  {
    participant_id: 'P18',
    name: 'Tanya Oberoi',
    age: '26',
    gender: 'F',
    city: 'Mumbai',
    occupation: 'Chartered Accountant',
    education: 'Chartered Accountant, ICAI',
    annual_income: 'INR 17 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Non-drinker',
    diet: 'Vegetarian',
    love_language: 'Acts of Service',
    perfect_sunday: 'Honestly, a solid gym session or a long run, maybe followed by getting lost in a good book for a few hours if I have the energy.',
    core_value: 'Probably being spiritual -- I try to stay grounded through my faith and a bit of quiet reflection each day.',
    shows_care_via: 'I show up and do things for them -- that\'s how I say it best.',
    quality_time_means: 'I show up and do things for them -- that\'s how I say it best, that\'s really what quality time means to me.',
    planning_style: 'I like routine and know what works for me, so I guess that answers it.',
    deal_breaker: 'Wanting completely different things out of life is the big one, and honestly heavy drinking is something I really can\'t be around long-term too.',
    friends_describe_you: 'Someone who listens first and picks their words carefully -- that\'s usually what people say about me.',
    relationship_goal: 'Honestly, I\'m here for marriage -- I\'m not looking to waste anyone\'s time.',
    favorite_hobby: 'A solid gym session or a long run -- I could genuinely talk about it for hours.',
    conflict_style: 'Easygoing and warm, someone people feel comfortable around, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more compassionate instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do getting lost in a good book for a few hours, with good food and no fixed plan.',
    family_importance: 'family comes first for me, always -- I try to make time for them no matter how busy things get.',
    first_impression: 'People usually notice I\'m someone who listens first and picks their words carefully.'
  },
  {
    participant_id: 'P19',
    name: 'Tara Bhatt',
    age: '29',
    gender: 'F',
    city: 'Mumbai',
    occupation: 'Marketing Lead',
    education: 'MBA Marketing, SIMC Pune',
    annual_income: 'INR 23 LPA',
    relationship_history: 'Never married',
    children_preference: 'Wants children',
    smoking_habit: 'Non-smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Gifts',
    perfect_sunday: 'Honestly, a trail I haven\'t done before, maybe followed by a solid gym session or a long run if I have the energy.',
    core_value: 'Probably being ambitious -- I\'m pretty driven -- I always want to be building toward something bigger.',
    shows_care_via: 'I like to surprise them with something small and thoughtful, just because.',
    quality_time_means: 'I like to surprise them with something small and thoughtful, just because, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly I struggle with someone who has no drive or direction too.',
    friends_describe_you: 'A bit quiet at first, but very steady once you get to know me -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'A trail I haven\'t done before -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more intellectual instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do a solid gym session or a long run, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m a bit quiet at first, but very steady once you get to know me.'
  },
  {
    participant_id: 'P20',
    name: 'Vivaan Kapoor',
    age: '31',
    gender: 'M',
    city: 'Delhi',
    occupation: 'Journalist',
    education: 'B.A. Journalism, Delhi University',
    annual_income: 'INR 14 LPA',
    relationship_history: 'Never married',
    children_preference: 'Open either way',
    smoking_habit: 'Occasional smoker',
    drinking_habit: 'Social drinker',
    diet: 'Non-vegetarian',
    love_language: 'Words of Affirmation',
    perfect_sunday: 'Honestly, a few hours lost in a good game, maybe followed by a trail I haven\'t done before if I have the energy.',
    core_value: 'Probably being intellectual -- I love a good debate or a book that makes me think differently.',
    shows_care_via: 'I tell them, out loud and often -- a genuine compliment goes a long way with me.',
    quality_time_means: 'I tell them, out loud and often -- a genuine compliment goes a long way with me, that\'s really what quality time means to me.',
    planning_style: 'I get bored easily and love mixing things up, so I guess that answers it.',
    deal_breaker: 'Someone who shuts down instead of talking things through, and honestly wanting completely different things out of life is the big one too.',
    friends_describe_you: 'A bit quiet at first, but very steady once you get to know me -- that\'s usually what people say about me.',
    relationship_goal: 'I want something long-term and serious, marriage down the line if it\'s right.',
    favorite_hobby: 'A few hours lost in a good game -- I could genuinely talk about it for hours.',
    conflict_style: 'A straight shooter who won\'t sugarcoat things, though I try to actually resolve things rather than let them sit.',
    social_style: 'Quieter, more of a one-on-one person.',
    self_improvement_area: 'Probably patience -- and being a bit more loyal instead of overthinking everything.',
    ideal_getaway: 'Somewhere I can do a trail I haven\'t done before, with good food and no fixed plan.',
    family_importance: 'A fair amount -- I check in with them regularly even when life gets busy.',
    first_impression: 'People usually notice I\'m a bit quiet at first, but very steady once you get to know me.'
  }
];

/**
 * Look up a single raw profile by participant_id.
 * @param {string} id - The participant_id to search for (e.g. 'P01')
 * @returns {object|undefined} The matching raw profile object, or undefined if not found
 */
export function getRawProfile(id) {
  return rawProfiles.find(p => p.participant_id === id);
}
